name: Update Python 3.12 Patch Version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC

jobs:
  update-python:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run update script
        run: python update_python_patch.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore: update Python 3.12 patch version in Dockerfile'
          branch: update-python-patch
          create_branch: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: update-python-patch
          title: 'Update Python 3.12 patch version in Dockerfile'
          body: 'This PR updates the Dockerfile to use the latest Python 3.12.x patch version.'